# Use root/example as user/password credentials
version: '3.3'

services:

  mariadb:
    image: mariadb:latest
#    platform: linux/amd64
#    build:
#        context: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D4pp3rExt3ns1ons 
      MYSQL_DATABASE: dapperTest
      MYSQL_USER: dapperExtensions
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
      - 33306:3306

  adminer:
    image: adminer
#    platform: linux/amd64
    depends_on: [mariadb]
#    build:
#        context: ./adminer
    restart: always
    ports:
      - 8080:8080

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
#    platform: linux/amd64
#    build:
#        context: ./oracle
    restart: always
    environment:
      ORACLE_CHARACTERSET: AL32UTF8
      ORACLE_ALLOW_REMOTE: 1
      ORACLE_DISABLE_ASYNCH_IO: 1
      ORACLE_ENABLE_XDB: 1
    ports:
      - 51521:1521
      - 1521:1521 
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
#    platform: linux/amd64
#    build:
#        context: ./sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: D4pp3rExt3ns1ons
    ports:
      - 1433:1433
